### PR TITLE
Rqueztech

### PR DESCRIPTION
**Pull request by rqueztech**
# Description

Added 18 ports that were previously not accounted for in the previous struct under registered ports.

Fixes # (18)

## Type of change

Please delete options that are not relevant.

- [ ] Added Data, new ports

# How Has This Been Tested?

Ran the main file to test if the new ports are being retrieved. Made sure nothing was off about how the elements were added.

# Checklist:

- [x] My code has been linted (`make lint`)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have rebased my branch to include the latest changes from `master`

### CODE REVIEW

**Comment by dnnrly** [comment]
Hi, thanks so much for the contribution! There's no need to update the Readme with details of updates carried out as the Git history is sufficient for this project. If you can remove that change then I can merge the rest. 😄

**Review by dnnrly — CHANGES_REQUESTED** [review]
This should be removed.

**Comment by rqueztech** [comment]
Howdy howdy! Just removed that pesky vandalizing of the README file :). If there is any other issues please feel free to let me know!

**Review by dnnrly — APPROVED** [review]

**Comment by dnnrly** [comment]
Thanks for the contribution!

**Pull request merged**
