### PR TITLE
georgettica/fix main acceptance

### PR DESCRIPTION
**Pull request by georgettica**
- fix(acceptance): use local binary
- refactor(test): make style conformnt #28

### CODE REVIEW

**Comment by georgettica** [comment]
this currently fails on 2 tests.. investigating now

**Comment by georgettica** [comment]
ready for review @dnnrly

**Comment by dnnrly** [comment]
Any chance you can re-open this PR, I fixed all of the problems that stopped it from building in master. I think this work is good. It's just a pity the PR validation let us down.

**Comment by georgettica** [comment]
I can, but what would you want me to do now?

**Pull request merged**
