### PR TITLE
refactor(test): use godog #21

### PR DESCRIPTION
**Pull request by georgettica**

### CODE REVIEW

**Comment by georgettica** [comment]
I saw that too, and it's not a hard fix

To be fair, this change is not a drop-in replacement.
I hope this will be helpful in the long run :)

**Comment by dnnrly** [comment]
I don't know if it helps, but in another of my projects I already use godog (hence wanting to do the same for this one). Here's what it looks like:
https://github.com/dnnrly/hoofli/tree/master/test

**Comment by georgettica** [comment]
it does, and I am sad I didn't use it before (as it looks very neat

**Comment by dnnrly** [comment]
No, that's on me. I raised the issue as a TODO for me originally so I skipped some of the notes I should have left.

**Comment by georgettica** [comment]
anyways.. now all is here.

do you want me to use your templates or are mine good enough?

**Comment by georgettica** [comment]
did changes requested :) and also fixed the test README.md

**Comment by georgettica** [comment]
will do, as swag is very important XD

**Comment by georgettica** [comment]
almost forgot to remove the bats file 🍀

**Comment by georgettica** [comment]
i'll fmt it now.. odd that vim didn't do that automatically

**Comment by dnnrly** [comment]
Apologies for the slow drip feed of comments. I'm away from my laptop tonight so having to use my phone. 🤷‍♂️

**Comment by georgettica** [comment]
it's ok. you are very quick in comparison to others XD

fixed manually

**Comment by georgettica** [comment]
@dnnrly can you add the `hacktoberfest-accepted` label?

see https://hacktoberfest.digitalocean.com/resources/maintainers for details

**Comment by dnnrly** [comment]
I was literally just looking for the label name. 😅

**Comment by dnnrly** [comment]
Also I have a tradition of following contributors on twitter. Is that alright with you? What's your Twitter handle?

**Pull request merged**
