### PR TITLE
Add HTML Elements Reference

### PR DESCRIPTION
**Pull request by selborsolrac**
# Description

This pull request adds an `html` subcommand that references HTML elements documented in MDN docs https://developer.mozilla.org/en-US/docs/Web/HTML.

Fixes https://github.com/dnnrly/httpref/issues/24

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Running existing tests
- [x] Created new tests

The following commands were also run to verify functionality
```
./bin/httpref html
./bin/httpref html \<i\>
./bin/httpref \<i\>
./bin/httpref --titles
./bin/httpref --help
./bin/httpref html --help
```

# Checklist:

- [x] My code has been linted (`make lint`)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have rebased my branch to include the latest changes from `master`

### CODE REVIEW

**Comment by dnnrly** [comment]
I think this is actually quite an important change! You seem to have covered an awful lot, if not all the HTML elements that anyone would care to look up.

Given the scale, I think it would be great to extend the tool a little more to support HTML specifically. First of all, I think we should probably add a little documentation to README.md to signpost this new capability.

I think something else that would be interesting would be the ability to search HTML without the need for the leading `<`. I think you've done the right thing here by including it in the reference. I'm just wondering if there's an opportunity to optimise the user's experience a little.

Now, I don't know quite how this would work yet and I'd be interested in your thoughts. It might be that this is more suitable for another PR if you can't see an easy solution for this one.

If that's the case, how would you feel about raising an enhancement issue for it?

**Comment by dnnrly** [comment]
Hi @selborsolrac, did you have any thoughts on how you'd like to approach this? Honestly, if you just want to add a little to the docs then I'm very happy to merge the PR - or I can do it if you prefer.

**Comment by selborsolrac** [comment]
Hello, sorry for the delay in my response. I'd be happy to update the PR with some additional documentation for the html elements.

I spent some time trying to come up with a way to allow for looking up html elements without the brackets but didn't come up with anything I was happy with. I can think about it some more and submit PR if I come up with something I like.

**Comment by dnnrly** [comment]
Yes, just add the docs for now. I'll take another look at the code to remind myself about it too.

**Comment by dnnrly** [comment]
Would you mind adding another `Scenario` to `test/features/cli.feature`? This will just to prove that the new sub-command is plumbed in correctly.

**Comment by selborsolrac** [comment]
Sure thing! I'll be sure to add a testing scenario.

**Comment by selborsolrac** [comment]
I updated the README and added a handful of scenarios to `test/features/cli.feature`. Let me know if you'd like any additional changes!

**Pull request merged**
