### PR TITLE
fix(acceptance): use local binary

### PR DESCRIPTION
**Pull request by georgettica**
my local setup used the `go-install`ed version and not the local one, thus the PATH didn't recognize it
solved by saving the binary in the `./bin` folder

### CODE REVIEW

**Comment by georgettica** [comment]
❤️

**Comment by georgettica** [comment]
I think it doesn't register if you don't add the `hacktoberfest` label 😱

**Comment by dnnrly** [comment]
Done.

**Comment by georgettica** [comment]
🎆 
working on the migration aswell :)

**Pull request merged**
